//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int id { get; set; }
        public int statusId { get; set; }
        public string article { get; set; }
        public int orderNumber { get; set; }
        public int quentity { get; set; }
        public System.DateTime dateOfOrder { get; set; }
        public System.DateTime pickUpDate { get; set; }
        public int pickUpPoint { get; set; }
        public string FIO { get; set; }
        public int PickUpCode { get; set; }
    
        public virtual pickUpPoint pickUpPoint1 { get; set; }
        public virtual statusId statusId1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
